name: anytime_todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^6.2.1
  awesome_snackbar_content: ^0.1.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  smooth_page_indicator: ^1.2.0+3

  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  flutter_slidable: ^3.1.1

# ----------------------- ./ PACKAGES END ----------------------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#-------------- Native Splash Oluşturma --------------#
# Terminale şunu yaz: flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/logo-todo.png
  image_dark: assets/logos/logo-todo.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/logo-todo.png
    image_dark: assets/logos/logo-todo.png
  
  web: false
#------------------------ ./ ------------------------#




flutter:
  uses-material-design: true

  # ----------------------- LOCAL ASSETS ----------------------- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  #-------------- LOCAL FONTS --------------#
  fonts:
    - family: ErasBold
      fonts:
        - asset: assets/fonts/ErasBoldITC.ttf
    - family: OhChewy
      fonts:
        - asset: assets/fonts/Oh-Chewy.ttf
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative-Medium.ttf

